### PR TITLE
add schema support

### PR DESCRIPTION
**Pull request by eugenemiretsky**
Allow passing a PubSub schema while creating a topic

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.bFKHhW8QH3/generate_docs/workspace/README.md
67a68
> | schema\_settings | Settings for validating messages published against a schema. | `map(any)` | `{}` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./variables.tf
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
main.tf
--- old/main.tf
+++ new/main.tf
@@ -97,8 +97,8 @@
   dynamic "schema_settings" {
     for_each = var.schema_settings
     content {
-      schema       = lookup(schema_settings.value, "schema", null)
-      encoding     = lookup(schema_settings.value, "encoding", null)
+      schema   = lookup(schema_settings.value, "schema", null)
+      encoding = lookup(schema_settings.value, "encoding", null)
     }
   }
 }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by eugenemiretsky** [comment]
Fixed CLA. Can we rescan please?

**Comment by morgante** [comment]
You need to sign with your `eugene@paytm.com` email as well.

**Comment by eugenemiretsky** [comment]
> You need to sign with your `eugene@paytm.com` email as well.

I actually have no idea why eu***e​@paytm.com is being used - it is my old email, and I cannot find it anywhere in my github settings.

**Comment by morgante** [comment]
Your commits are signed with it. You can find more info here: https://github.com/terraform-google-modules/terraform-google-pubsub/pull/82/checks?check_run_id=4539285893

**Pull request closed without merging**
