### PR TITLE
feat!: remove grant_token_creator

### PR DESCRIPTION
**Pull request by naseemkullah**
closes https://github.com/terraform-google-modules/terraform-google-pubsub/issues/106

cc @anakovt 

> When you have a push subscription with OIDC enabled, you need to have `roles/iam.serviceAccountTokenCreator` role added to Pub/Sub’s default SA. But if you would remove one subscription with all its resources it will delete a role as well, but some other subscriptions might still need to use it since there is just one default Pub/Sub service account per project.
>
> This role should be added on the project-factory-module level after you check that the Pub/Sub API is enabled.
- <https://github.com/terraform-google-modules/terraform-google-pubsub/pull/48#issue-762410597>

As per the above comment, we are deprecating the use of `grant_token_creator`, to ensure that the `google_project_iam_member.token_creator_binding` does not get
accidentally deleted, we are removing any default value for `grant_token_creator` and asking that users remove the resource from within this module's terraform state and set the variable to `false`. Failure to remove/move the state of the resource prior to setting the variable to `false` can result in push subscriptions with OIDC enabled failing.

edit: removing the option altogether as per @bharathkkb's [suggestion](https://github.com/terraform-google-modules/terraform-google-pubsub/pull/109#pullrequestreview-1176533433)

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/bigquery
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 21, in module "pubsub":
│
 
  21: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on ../../modules/cloudiot/main.tf line 87, in module "state_notification_topic":
│
 
  87: module "state_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/kms
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 50, in module "pubsub":
│
 
  50: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/simple
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 21, in module "pubsub":
│
 
  21: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/subscriptions_only
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 26, in module "pubsub":
│
 
  26: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./modules/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 76, in module "event_notification_topic":
│
 
  76: module "event_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./test/setup
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 35, in module "project-ci-int-pubsub":
│
 
  35:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
 ```

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/bigquery
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 21, in module "pubsub":
│
 
  21: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on ../../modules/cloudiot/main.tf line 76, in module "event_notification_topic":
│
 
  76: module "event_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/kms
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 50, in module "pubsub":
│
 
  50: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/simple
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 21, in module "pubsub":
│
 
  21: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/subscriptions_only
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 26, in module "pubsub":
│
 
  26: module "pubsub" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./modules/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 76, in module "event_notification_topic":
│
 
  76: module "event_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./test/setup
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 35, in module "project-ci-int-pubsub":
│
 
  35:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
 ```

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/bigquery
Success!
 The configuration is valid.
terraform_validate ./examples/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on ../../modules/cloudiot/main.tf line 76, in module "event_notification_topic":
│
 
  76: module "event_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./examples/kms
Success!
 The configuration is valid.
terraform_validate ./examples/simple
Success!
 The configuration is valid.
terraform_validate ./examples/subscriptions_only
Success!
 The configuration is valid.
terraform_validate ./modules/cloudiot
╷
│
 
Error: 
Missing required argument
│
 
│
 
  on main.tf line 87, in module "state_notification_topic":
│
 
  87: module "state_notification_topic" 
{
│
 
│
 
The argument "grant_token_creator" is required, but no definition was
│
 
found.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by naseemkullah** [comment]
@bharathkkb PTAL 🙏

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @naseemkullah 
Can we remove altogether than making it required?
If pubsub supports service identity, it would be good to showcase an example with project factory in the migration guide.
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/97d0a99d865dc10fee72c7e467417dded930508e/variables.tf#L110-L123

**Comment by naseemkullah** [comment]
> Thanks for the PR @naseemkullah Can we remove altogether than making it required? If pubsub supports service identity, it would be good to showcase an example with project factory in the migration guide. https://github.com/terraform-google-modules/terraform-google-project-factory/blob/97d0a99d865dc10fee72c7e467417dded930508e/variables.tf#L110-L123

I thought the 2-step approach of making users set it to `false` explicitly would be slightly safer, but we can do it in one step with a migration guide. Your call, lmk!

**Comment by apeabody** [comment]
Thanks for the PR @naseemkullah! - If you are still working on this PR we can try to include in #105.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/README.md /tmp/tmp.6Q8F2v32hC/generate_docs/workspace/README.md
73d72
< | grant\_token\_creator | Deprecated - IMPORTANT: Remove (or move), if present, this module's `google_project_iam_member.token_creator_binding` resource from terraform state before explicitly setting value to false. | `bool` | n/a | yes |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/bigquery
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 30, in module "pubsub":
│
 
  30:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
terraform_validate ./examples/cloudiot
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../modules/cloudiot/main.tf line 85, in module "event_notification_topic":
│
 
  85:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
terraform_validate ./examples/kms
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 56, in module "pubsub":
│
 
  56:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
terraform_validate ./examples/simple
Success!
 The configuration is valid.
terraform_validate ./examples/subscriptions_only
Success!
 The configuration is valid.
terraform_validate ./modules/cloudiot
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 85, in module "event_notification_topic":
│
 
  85:   
grant_token_creator
 = false
│
 
│
 
An argument named "grant_token_creator" is not expected here.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@naseemkullah
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by naseemkullah** [comment]
Thanks, removed altogether, ptal @bharathkkb @apeabody

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
ptal

**Comment by naseemkullah** [comment]
helloooooooooooo

**Pull request closed without merging**
