### PR TITLE
feat(TPG>=6.2)!: add cloud storage max_messages and use_topic_schema support

### PR DESCRIPTION
**Pull request by lahuang4**
Adding support to terraform-google-pubsub following adding support in the provider: https://github.com/hashicorp/terraform-provider-google/pull/19338

Similar to https://github.com/terraform-google-modules/terraform-google-pubsub/pull/192, I'm having trouble getting the example in `examples/cloud_storage` pick up the new fields. Running `terraform plan` still ignores the specified filename_datetime_format field which was [added](https://github.com/terraform-google-modules/terraform-google-pubsub/blob/master/examples/cloud_storage/main.tf#L43) in the previous PR:

```
terraform-google-pubsub/examples/cloud_storage$ terraform plan
var.project_id
  The project ID to manage the Pub/Sub resources

  Enter a value: <project>

...

Terraform will perform the following actions:

...

  # module.pubsub.google_pubsub_subscription.cloud_storage_subscriptions["example_bucket_subscription"] will be created
  + resource "google_pubsub_subscription" "cloud_storage_subscriptions" {
      + ack_deadline_seconds       = 300
      + effective_labels           = (known after apply)
      + id                         = (known after apply)
      + message_retention_duration = "604800s"
      + name                       = "example_bucket_subscription"
      + project                    = "<project>"
      + terraform_labels           = (known after apply)
      + topic                      = "cft-tf-pubsub-topic-cloud-storage"

      + cloud_storage_config {
          + bucket          = (known after apply)
          + filename_prefix = "example_prefix_"
          + filename_suffix = "_example_suffix"
          + max_duration    = "300s"
          + state           = (known after apply)
        }
    }

...

Plan: 6 to add, 0 to change, 0 to destroy.
```

Would appreciate any tips for debugging this, but otherwise the change seems complete, so I'm sending it for review. Thanks!

### CODE REVIEW

**Comment by lahuang4** [comment]
Hi, another nudge on this PR!

**Comment by apeabody** [comment]
Hi @lahuang4 - I pull a fresh/current copy of the repo and it's worked for me:

```
  # module.pubsub.google_pubsub_subscription.cloud_storage_subscriptions["example_bucket_subscription"] will be created
  + resource "google_pubsub_subscription" "cloud_storage_subscriptions" {
      + ack_deadline_seconds       = 300
      + effective_labels           = (known after apply)
      + id                         = (known after apply)
      + message_retention_duration = "604800s"
      + name                       = "example_bucket_subscription"
      + project                    = "ap-bps-experimental-gke"
      + terraform_labels           = (known after apply)
      + topic                      = "cft-tf-pubsub-topic-cloud-storage"

      + cloud_storage_config {
          + bucket                   = (known after apply)
          + filename_datetime_format = "YYYY-MM-DD/hh_mm_ssZ"
          + filename_prefix          = "example_prefix_"
          + filename_suffix          = "_example_suffix"
          + max_duration             = "300s"
          + state                    = (known after apply)
        }

      + expiration_policy (known after apply)
    }
```

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @lahuang4!

LGTM - @imrannayer?

**Pull request merged**
