### PR TITLE
feat(TPG>=5.31)!: add cloud storage filename datetime format support

### PR DESCRIPTION
**Pull request by lahuang4**
I've tried to add support for this new field following https://github.com/GoogleCloudPlatform/magic-modules/pull/10713. However, I'm having some trouble with having the example in `examples/cloud_storage` pick up the new filename_datetime_format field (it seems to be ignored).

With the updated example which attempts to set filename_prefix, filename_suffix, and filename_datetime_format, I get this with `terraform plan`:

```sh
terraform-google-pubsub/examples/cloud_storage$ terraform init -upgrade

Initializing the backend...
Upgrading modules...
Downloading registry.terraform.io/terraform-google-modules/pubsub/google 6.0.0 for pubsub...
- pubsub in .terraform/modules/pubsub

Initializing provider plugins...
- Finding hashicorp/google versions matching ">= 4.78.0, < 6.0.0"...
- Finding latest version of hashicorp/random...
- Using previously-installed hashicorp/google v5.31.1
- Using previously-installed hashicorp/random v3.6.2

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.



terraform-google-pubsub/examples/cloud_storage$ terraform plan
var.project_id
  The project ID to manage the Pub/Sub resources

  Enter a value: <project>

...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.pubsub.google_pubsub_subscription.cloud_storage_subscriptions["example_bucket_subscription"] will be created
  + resource "google_pubsub_subscription" "cloud_storage_subscriptions" {
      + ack_deadline_seconds       = 300
      + effective_labels           = (known after apply)
      + id                         = (known after apply)
      + message_retention_duration = "604800s"
      + name                       = "example_bucket_subscription"
      + project                    = "<project>"
      + terraform_labels           = (known after apply)
      + topic                      = "cft-tf-pubsub-topic-cloud-storage"

      + cloud_storage_config {
          + bucket          = "test_bucket-ed5de96a"
          + filename_prefix = "example_prefix_"
          + filename_suffix = "_example_suffix"
          + max_duration    = "300s"
          + state           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

I suspect that the issue might be because the example seems to be stubbornly requiring a version >= 4.78 even though I've changed the versions files to require version >= 5.31.

Would appreciate any insight you might have (maybe I implemented the provider incorrectly, but I'm surprised that it passes the tests in that repo if that's the case).

### CODE REVIEW

**Comment by lahuang4** [comment]
A friendly bump on this, Imran :)

**Comment by imrannayer** [comment]
@lahuang4 can u plz add a doc in [doc folder] detailing breaking change?

**Comment by lahuang4** [comment]
> @lahuang4 can u plz add a doc in [doc folder] detailing breaking change?

Should this look something like https://github.com/terraform-google-modules/terraform-google-pubsub/blob/master/docs/upgrading_to_v2.0.md? I'm not sure what version number will be released next (I'd guess v7.0?).

I thought that the breaking change would automatically be included in the version's release notes, similar to the breaking changes listed in https://github.com/terraform-google-modules/terraform-google-pubsub/releases/tag/v6.0.0 -- do I still need to add a doc?

Thanks!

**Comment by imrannayer** [comment]
@lahuang4 yes breaking change will be in change. Next version will be 7.0. You can create upgrade docs.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
